### ISSUE TITLE
Place `yassgy` into a library file

### ISSUE THREAD

**Issue by dbelokon** [JerryHue/yassgy#17]
When I was reading how to add integrations tests to binary crates in the Learn Rust book, the section ["Integration Tests for Binary crates"](https://doc.rust-lang.org/book/ch11-03-test-organization.html#integration-tests-for-binary-crates) says that "Only library crates expose functions that other crates can use; binary crates are meant to be run on their own."

This means that I cannot call the code from the `static_site.rs` in by test files, because the binary file, `main.rs`, does not expose them.

I think we will need to reveal the functionality from the `lib.rs` file.

**Comment by JerryHue** [comment]
You are right. The integration tests placed in the `tests` folder cannot access the functions in any of the other files.

I will follow up with a PR to address this.
