### ISSUE TITLE
Non-.txt files are also processed

### ISSUE THREAD

**Issue by DukeManh** [JerryHue/yassgy#2]
None `.txt` files are not skipped, including `image/*`. Such file could contain invalid text which causes the program to crash.

**Comment by JerryHue** [comment]
Indeed, I need to validate whether the passed filename has a proper ".txt" extension or not.

I am not sure if you have access to a Windows environment, but if you do, could you run `./yassgy -i *.txt` or `cargo run -- -i *.txt`? I read in the documentation that files with wildcard patterns do not get expanded on Windows, so I am wondering if it will try to find a file named `*.txt` or something like that. I will run the same use case on my environment, as well.

**Comment by DukeManh** [comment]
On my Mac machine, the wildcard is not expanded.
![image](https://user-images.githubusercontent.com/51073515/133648915-d8745184-1003-4578-91fb-c30b4e0db491.png)
