### ISSUE TITLE
Incosistent spacing, and comma

### ISSUE THREAD

**Issue by DukeManh** [JerryHue/yassgy#3]
It looks like you are not using Rust language server for linting and formatting. I suggest you install [Rust Extension](https://marketplace.visualstudio.com/items?itemName=rust-lang.rust) if you are using VSCode or start the language server if you already have it installed.
The formatted files would look like this #1

**Comment by JerryHue** [comment]
I noticed that the indenting is not proper to how some Rust projects deal with indenting. If you run `rustfmt src/*`, it will recommend 4 spaces for indenting instead of tabs.

Checking your PR, I notice that the file seems to use tabs for indenting. Could you try to run the command `rustfmt src/*` to see what `rustfmt` recommends? It might be different or not, but for me it shows the following:

```
Diff in /home/gerardo/workspace/yassgy/src/html_page.rs at line 1:
 use std::fs::File;
+use std::io::{BufRead, BufReader, Result, Write};
 use std::path;
-use std::io::{BufReader, BufRead, Write, Result};
-    
+
 pub struct HtmlPage {
     html_body: String,
 }
Diff in /home/gerardo/workspace/yassgy/src/html_page.rs at line 8:
 
 impl HtmlPage {
     pub fn from<P: AsRef<path::Path>>(file_name: P) -> Result<HtmlPage> {
-	let file = File::open(file_name)?;
-	let buf_reader = BufReader::new(file);
+        let file = File::open(file_name)?;
+        let buf_reader = BufReader::new(file);
 
-	let mut lines: Vec<String> = Vec::new();
+        let mut lines: Vec<String> = Vec::new();
 
-	for line_result in buf_reader.lines() {
-	    lines.push(line_result?);
-	}
-	    
-	let html_body = lines.split(|l| l.trim().is_empty())
-	    .filter(|&v| !v.is_empty())
-	    .map(|v| v.join("<br />"))
-	    .map(|p| format!("<p>{}</p>", p))
-	    .fold(String::new(), |mut acc, p| {
-		acc.push_str(&p);
-		acc
-	    });
-	    
-	Ok(HtmlPage { html_body })
+        for line_result in buf_reader.lines() {
+            lines.push(line_result?);
+        }
+
+        let html_body = lines
+            .split(|l| l.trim().is_empty())
+            .filter(|&v| !v.is_empty())
+            .map(|v| v.join("<br />"))
+            .map(|p| format!("<p>{}</p>", p))
+            .fold(String::new(), |mut acc, p| {
+                acc.push_str(&p);
+                acc
+            });
+
+        Ok(HtmlPage { html_body })
     }
//...
}
```

Notice the individual spaces for the `+` lines.

**Comment by JerryHue** [comment]
Either way, I will try to configure `clippy` and `rustfmt` to run before each commit for the future commits.

Thank you for the reminder.

**Comment by DukeManh** [comment]
Ok, I'll try that. 
You can close the PR and push the new code with your own format. I just want to give you an idea of what the formatted files could look like.
