### ISSUE TITLE
Potential improvement

### ISSUE THREAD

**Issue by DukeManh** [JerryHue/yassgy#5]
https://github.com/JerryHue/yassgy/blob/b0691fae37d6240d4ea26d6a06256be4face83d0/src/main.rs#L65

Reading this part, I wonder if you can reduce the code from line 64 to 79 to a single function call instead of chaining operations on `input_dir_entries`. I'm not sure how that could be done in Rust, maybe by calling `fold`, but here's my idea written in TS.  

```
// Using reduce to return accumulated array of filtered value
input_dir_entries.reduce((acc, file) => {
  try {
    const stats = fs.statSync(file);
    return stats.isFile() ? acc.concat(file) : acc;
  } catch {
    return acc;
  }
}, []);

```
That way we only loop the folder once to get the desired array. 
This may not be syntactically possible in Rust

**Comment by DukeManh** [comment]
https://github.com/JerryHue/yassgy/blob/b0691fae37d6240d4ea26d6a06256be4face83d0/src/html_page.rs#L21
Is this call necessary when you already split and remove the blank lines above.

**Comment by DukeManh** [comment]
https://github.com/JerryHue/yassgy/blob/b0691fae37d6240d4ea26d6a06256be4face83d0/src/html_page.rs#L22
Another improvement is to not put ` <br> `at the end of every line to let the next line follow where the previous line ends.
On small screens that would result in weird line breaks.
<img width="299" alt="image" src="https://user-images.githubusercontent.com/51073515/133736087-93d36200-b59d-4d71-aa69-1a262a42305b.png">
On large screens, that would result in less text is displayed than possible. 

<img width="1126" alt="image" src="https://user-images.githubusercontent.com/51073515/133736218-d9e8e907-40ab-46c9-9818-43e8186c8eef.png">

**Comment by JerryHue** [comment]
> https://github.com/JerryHue/yassgy/blob/b0691fae37d6240d4ea26d6a06256be4face83d0/src/main.rs#L65
> 
> Reading this part, I wonder if you can reduce the code from line 64 to 79 to a single function call instead of chaining operations on `input_dir_entries`. I'm not sure how that could be done in Rust, maybe by calling `fold`, but here's my idea written in TS.
> 
> ```
> // Using reduce to return accumulated array of filtered value
> input_dir_entries.reduce((acc, file) => {
>   try {
>     const stats = fs.statSync(file);
>     return stats.isFile() ? acc.concat(file) : acc;
>   } catch {
>     return acc;
>   }
> }, []);
> ```
> 
> That way we only loop the folder once to get the desired array.
> This may not be syntactically possible in Rust

So, the runtime performance of iterators in Rust is sometimes... unpredictable, to say the least.

While it is indeed true that it several iterators may be run as several loops, this may not be as undesirable as you might think, see [this](https://gamedev.stackexchange.com/questions/157001/why-do-separate-loops-run-faster-than-one-loop-that-does-multiple-things).

In my latest commit, I got rid of the iterator and used regular loops to do the tasks I needed to do, mainly because I didn't know how to write the code to use with iterators.

**Comment by JerryHue** [comment]
> https://github.com/JerryHue/yassgy/blob/b0691fae37d6240d4ea26d6a06256be4face83d0/src/html_page.rs#L21
> 
> Is this call necessary when you already split and remove the blank lines above.

Indeed, it is, since there is a subtle detail with the filter function, see Rust docs for [Iterator::filter](https://doc.rust-lang.org/std/iter/trait.Iterator.html#method.filter). Filter will not pass the `Vec` elements that are empty, that is, the `Vec` that contained empty lines. If I do not filter them, an empty paragraph element may be added.

**Comment by JerryHue** [comment]
> https://github.com/JerryHue/yassgy/blob/b0691fae37d6240d4ea26d6a06256be4face83d0/src/html_page.rs#L22
> 
> Another improvement is to not put `<br>`at the end of every line to let the next line follow where the previous line ends.
> On small screens that would result in weird line breaks.
> <img alt="image" width="299" src="https://user-images.githubusercontent.com/51073515/133736087-93d36200-b59d-4d71-aa69-1a262a42305b.png">
> On large screens, that would result in less text is displayed than possible.
> 
> <img alt="image" width="1126" src="https://user-images.githubusercontent.com/51073515/133736218-d9e8e907-40ab-46c9-9818-43e8186c8eef.png">

This error was a misunderstanding by my part, as I thought that we need to preserve the breaking of the lines as shown in the text file.

I haven't made the change to not add `<br />` yet, but I will implement it in a future commit.
